spring.application.name=RestAPIFurb

server.port=8080
server.servlet.context-path=/RestAPIFurb
spring.datasource.url=jdbc:mysql://localhost:3306/rest_api_furb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.default-property-inclusion=non_null

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=RHVwYVJlc3RBUElGdWJyaWNhMjAyNlN1cGVyU2VjcmV0S2V5
app.jwt.expiration=3600000
